"""docs/reference.md is generated from the code (scripts/gen_reference.py) and must not drift.

(a) The drift gate: the committed file equals the generator's output.
(b) The committed file against values the tests read from the code themselves, without the
    generator: the package table, the Stockfish and Maia-2 pins, the win-rate rows and source,
    every CLI command and argument (type, default, choices, help), every UCI option (order,
    columns, ids, placeholders), the configuration-file sections (checked by loading real TOML
    files), every row of every dataclass table (type, docstring, scalar default), every cell of
    the persona table, the equation docstrings, the environment rows and the advisories. A
    generator bug in those rows, committed together with a file regenerated by it, passes (a)
    but fails here. The section intros, the constants table (section 10) and the
    ``sf19_expected_score`` docstring block are covered by (a) and (c) only.
(c) Unit tests that pin down each extraction and rendering rule of the generator.
"""

from __future__ import annotations

import argparse
import ast
import dataclasses
import functools
import html
import importlib
import importlib.util
import inspect
import io
import itertools
import json
import os
import re
import subprocess
import sys
import textwrap
import threading
import tomllib
from collections.abc import Callable, Iterator
from importlib import resources
from pathlib import Path, PurePosixPath, PureWindowsPath
from types import FunctionType, ModuleType, SimpleNamespace
from typing import Any

import pytest

import cca
from cca import config
from cca.agent import AgentConfig
from cca.chaos.baseline import AR1Params
from cca.chaos.lorenz import LorenzParams
from cca.cli import build_parser
from cca.config import list_personas
from cca.engines import stockfish
from cca.engines.maia2_human import PINNED_SHA256, verify_checkpoint
from cca.neuro.controller import Persona
from cca.neuro.neuromodulation import NeuroParams
from cca.timing.think_time import ThinkTimeParams
from cca.uci import protocol

ROOT = Path(__file__).resolve().parents[2]
REFERENCE = ROOT / "docs" / "reference.md"
GENERATOR = ROOT / "scripts" / "gen_reference.py"
SF_LINUX_SHA256 = "9defc0d4e55d49c65a6d042f3e571a39fcea499ade6dbe741b53b8c65e03611f"
CONFIG_CLASSES = (AgentConfig, Persona, NeuroParams, ThinkTimeParams, LorenzParams, AR1Params)
# The modules whose docstrings hold the model equations (the task that created the reference).
EQUATION_MODULES = (
    "cca.neuro.controller",
    "cca.neuro.neuromodulation",
    "cca.policy.pikl",
    "cca.policy.exploit",
    "cca.policy.distributions",
    "cca.chaos.lorenz",
    "cca.chaos.baseline",
    "cca.timing.think_time",
)
_SCALARS = (bool, int, float, str, type(None))
_CODE_SPAN = re.compile(r"(?<!`)(`+)(?!`).*?(?<!`)\1(?!`)")


def _load(path: Path, name: str) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def gen() -> Iterator[ModuleType]:
    name = "cca_script_gen_reference"
    spec = importlib.util.spec_from_file_location(name, GENERATOR)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module  # dataclasses resolve their module through sys.modules
    try:
        spec.loader.exec_module(module)
        yield module
    finally:
        del sys.modules[name]


@pytest.fixture(scope="module")
def committed() -> str:
    return REFERENCE.read_bytes().decode("utf-8")


def _rows(text: str, first_cell: str) -> list[str]:
    rows = [line for line in text.splitlines() if line.startswith(f"| {first_cell} |")]
    assert rows, f"no table row starting with {first_cell}"
    return rows


def _row(text: str, first_cell: str) -> str:
    return _rows(text, first_cell)[0]


def _cells(row: str) -> list[str]:
    """Cells of one table row (``\\|`` inside a cell is not a separator)."""
    assert row.startswith("| ")
    assert row.endswith(" |")
    return re.split(r"(?<!\\) \| ", row[2:-2])


def _section(text: str, heading: str) -> str:
    """The lines after ``heading`` up to the next heading (fenced code blocks skipped)."""
    lines = text.splitlines()
    start = lines.index(heading) + 1
    fence = ""
    for end in range(start, len(lines)):
        line = lines[end]
        if fence:
            fence = "" if line == fence else fence
        elif opening := re.match(r"`{3,}", line):
            fence = opening.group()
        elif line.startswith("#"):
            return "\n".join(lines[start:end])
    return "\n".join(lines[start:])


def _docstring(obj: object) -> str:
    """A docstring as the reference quotes it: cleaned, no trailing blanks on any line."""
    doc = inspect.cleandoc(getattr(obj, "__doc__", None) or "")
    return "\n".join(line.rstrip() for line in doc.splitlines())


def _primary_commands(
    parser: argparse.ArgumentParser,
) -> dict[str, tuple[argparse.ArgumentParser, list[str]]]:
    """``{command: (parser, aliases)}``: argparse registers a command before its aliases."""
    subs = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    names: dict[int, list[str]] = {}
    parsers: dict[int, argparse.ArgumentParser] = {}
    for name, child in subs._name_parser_map.items():
        names.setdefault(id(child), []).append(name)
        parsers[id(child)] = child
    return {found[0]: (parsers[key], found[1:]) for key, found in names.items()}


# --- (a) drift gate
def test_committed_reference_matches_the_code(
    gen: ModuleType, capsys: pytest.CaptureFixture[str]
) -> None:
    code = gen.main(["--check"])
    out = capsys.readouterr()
    assert code == 0, f"{out.err}\n{out.out}"
    assert "is up to date" in out.out


# --- (b) the committed file against the code, read here without the generator
def test_committed_reference_has_known_values(committed: str) -> None:
    fast = _row(committed, "`fast_budget`")
    assert "`0.6`" in fast
    assert "reflex mode" in fast  # the attribute docstring travels with the field
    assert SF_LINUX_SHA256 in committed
    assert PINNED_SHA256["rapid"] in committed
    persona_w0 = _rows(committed, "`w0`")[-1]  # the persona table comes after `Persona`
    assert "**`0.6`**" in persona_w0  # dubov overrides w0 = 0.60


def test_package_table_lists_pyproject_and_version(committed: str) -> None:
    pyproject = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    project = pyproject["project"]
    section = _section(committed, "## 1. Package")
    rows = set(section.splitlines())
    assert f"| Distribution | `{project['name']}` |" in rows
    assert f"| Version (`cca.__version__`) | `{cca.__version__}` |" in rows
    assert f"| Python | `{project['requires-python']}` |" in rows
    assert f"| Licence | `{project['license']}` |" in rows
    assert f"| Build backend | `{pyproject['build-system']['build-backend']}` |" in rows
    for group, entries in pyproject.get("dependency-groups", {}).items():
        for dep in entries:
            assert f"| Dependency group `{group}` | `{dep}` |" in rows
    for dep in project["dependencies"]:
        assert f"| Dependency | `{dep}` |" in rows
    for extra, deps in project.get("optional-dependencies", {}).items():
        for dep in deps:
            assert f"| Extra `{extra}` | `{dep}` |" in rows
    for name, target in project.get("scripts", {}).items():
        assert f"| Console script `{name}` | `{target}` |" in rows


def test_stockfish_rows_match_the_lock_file(committed: str) -> None:
    lock = json.loads((ROOT / "engines" / "stockfish.lock.json").read_text(encoding="utf-8"))
    fetch = _load(ROOT / "scripts" / "fetch_stockfish.py", "cca_test_fetch_stockfish")
    section = _section(committed, "### 2.1 Stockfish release assets")
    assert lock
    for key, sha in lock.items():
        tag, _, name = key.partition("/")
        url = fetch.DOWNLOAD.format(tag=tag, name=name)
        assert f"| `{key}` | `{sha}` | {url} |" in section.splitlines()
    assert _docstring(fetch) in section


def test_maia2_rows_match_the_pins(committed: str) -> None:
    section = _section(committed, "### 2.2 Maia-2 checkpoints")
    for kind, sha in PINNED_SHA256.items():
        assert f"| `{kind}` | `{sha}` |" in section.splitlines()
    assert " ".join(_docstring(verify_checkpoint).split()) in html.unescape(section)


def test_win_rate_rows_match_the_coefficients(committed: str) -> None:
    section = _section(committed, "### 2.3 Stockfish 17-19 win-rate model")
    rows = [line for line in section.splitlines() if re.match(r"\| \d+ \|", line)]
    pairs = zip(stockfish._WR_A, stockfish._WR_B, strict=True)
    assert rows == [f"| {i} | `{a!r}` | `{b!r}` |" for i, (a, b) in enumerate(pairs)]
    source = inspect.getsource(stockfish.sf19_expected_score).rstrip("\n").splitlines()
    assert "\n".join(line.rstrip() for line in source) in section


def test_committed_reference_documents_every_cli_command_and_flag(committed: str) -> None:
    commands = _primary_commands(build_parser())
    assert commands
    for name, (parser, aliases) in commands.items():
        section = _section(committed, f"### `cca {name}`")
        for alias in aliases:  # folded into the command, never a heading of its own
            assert f"`{alias}`" in section
            assert f"### `cca {alias}`" not in committed.splitlines()
        if parser.epilog:
            assert " ".join(parser.epilog.split()) in html.unescape(section)
        for action in parser._actions:
            if isinstance(action, (argparse._HelpAction, argparse._SubParsersAction)):
                continue
            flag = ", ".join(action.option_strings) or str(action.metavar or action.dest)
            cells = _cells(_row(section, f"`{flag}`"))
            assert cells[1].startswith(_expected_kind(action)), (flag, cells)
            if action.required:
                assert cells[2] == "*required*"
            elif isinstance(action.default, _SCALARS) and action.default != argparse.SUPPRESS:
                assert cells[2] == f"`{action.default!r}`", cells
            if isinstance(action.type, FunctionType) and action.type.__closure__:
                # a type made by a factory shows the values it captured
                bound = inspect.getclosurevars(action.type).nonlocals
                assert all(f"{k}={v!r}" in cells[1] for k, v in bound.items()), cells
            choices = ", ".join(f"`{c!r}`" for c in action.choices or ())
            assert cells[3] == choices, (flag, cells)
            assert _unescape_cell(cells[4]) == _expected_help(parser, action), (flag, cells)


def _expected_kind(action: argparse.Action) -> str:
    """The start of an argument's Type cell: flag, str, a class name or a return annotation."""
    if action.nargs == 0:
        return "flag"
    if action.type is None:
        return "str"
    if isinstance(action.type, FunctionType):
        returns = inspect.signature(action.type).return_annotation
        if returns is not inspect.Signature.empty:
            return returns if isinstance(returns, str) else returns.__name__
    return str(getattr(action.type, "__name__", ""))


def _expected_help(parser: argparse.ArgumentParser, action: argparse.Action) -> str:
    if action.help is None:
        return ""
    if action.help == argparse.SUPPRESS:
        return "(hidden from `--help`)"
    return " ".join(parser._get_formatter()._expand_help(action).split())


def _unescape_cell(cell: str) -> str:
    return html.unescape(cell.replace("\\|", "|"))


def _uci_lines() -> list[str]:
    out = io.StringIO()
    protocol.UciServer(stdin=io.StringIO("uci\nquit\n"), stdout=out).serve()
    return out.getvalue().splitlines()


def _uci_options() -> list[dict[str, str | list[str] | None]]:
    pattern = re.compile(
        r"option name (?P<name>.+?) type (?P<type>\S+)(?: default ?(?P<default>.*?))?"
        r"(?: min (?P<min>\S+))?(?: max (?P<max>\S+))?(?P<vars>(?: var .*?)*)"
    )
    found = []
    for line in _uci_lines():
        if line.startswith("option "):
            match = pattern.fullmatch(line)
            assert match is not None, line
            option: dict[str, str | list[str] | None] = dict(match.groupdict())
            option["vars"] = [v for v in (match["vars"] or "").split(" var ") if v]
            found.append(option)
    return found


def _code(value: str) -> str:
    assert "`" not in value
    return f"`{value}`" if value else "*(empty)*"


def test_committed_uci_rows_match_a_real_handshake(committed: str) -> None:
    options = _uci_options()
    assert options
    helps = getattr(protocol, "UCI_OPTION_HELP", {})
    section = _section(committed, "## 4. UCI options")
    for option in options:
        name, default, low, high, values = (
            option[k] for k in ("name", "default", "min", "max", "vars")
        )
        assert isinstance(name, str)
        cells = _cells(_row(section, f"`{name}`"))
        expected = [_code(v) if isinstance(v, str) else "" for v in (default, low, high)]
        assert cells[1:5] == [option["type"], *expected], cells
        assert isinstance(values, list)
        assert cells[5] == ", ".join(_code(v) for v in values), cells
        help_text = " ".join(helps.get(name, "").split())
        assert html.unescape(cells[6].replace("\\|", "|")) == help_text
    rows = [line for line in section.splitlines() if line.startswith("| `")]
    documented = [_cells(row)[0] for row in rows if len(_cells(row)) == 7]
    assert documented == [f"`{o['name']}`" for o in options]  # in the advertised order
    for line in _uci_lines():
        if line.startswith("id "):
            key, _, value = line[3:].partition(" ")
            assert f"| `{key}` | `{value}` |" in section.splitlines(), line
    placeholders = sorted(getattr(protocol, "_PLACEHOLDERS", ()))
    if placeholders:
        shown = ", ".join(f"`{p}`" for p in placeholders)
        assert f"Default placeholders that mean *unset*: {shown}." in section


def _public_dataclasses() -> list[type[Any]]:
    """Every public top-level dataclass in ``src/cca``, found by a text scan of the sources."""
    found: list[type[Any]] = []
    decorated = re.compile(
        r"^@(?:dataclasses\.)?dataclass\b.*\n(?:@.*\n)*class (\w+)", re.MULTILINE
    )
    for path in sorted((ROOT / "src" / "cca").rglob("*.py")):
        names = [n for n in decorated.findall(path.read_text(encoding="utf-8")) if n[0] != "_"]
        if names:
            parts = path.relative_to(ROOT / "src").with_suffix("").parts
            module = importlib.import_module(".".join(p for p in parts if p != "__init__"))
            found.extend(getattr(module, n) for n in names)
    return found


def _field_docs(cls: type[Any]) -> dict[str, str]:
    """``{field: attribute docstring}`` from the class source, whitespace folded."""
    tree = ast.parse(textwrap.dedent(inspect.getsource(cls)))
    body = next(n for n in tree.body if isinstance(n, ast.ClassDef)).body
    docs = {}
    for stmt, after in itertools.pairwise([*body, None]):
        if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
            value = None
            if isinstance(after, ast.Expr) and isinstance(after.value, ast.Constant):
                value = after.value.value
            docs[stmt.target.id] = " ".join(value.split()) if isinstance(value, str) else ""
    return docs


def _same_annotation(cell: str, annotation: object) -> bool:
    written = cell.replace("\\|", "|").removeprefix("`").removesuffix("`")
    if not isinstance(annotation, str):  # a module without ``from __future__ import annotations``
        return bool(written)
    dump = [ast.dump(ast.parse(a, mode="eval")) for a in (written, annotation)]
    return dump[0] == dump[1]


def test_committed_dataclass_tables_match_every_field(committed: str) -> None:
    classes = _public_dataclasses()
    assert set(CONFIG_CLASSES) <= set(classes)
    model = importlib.import_module("cca.core.types")
    in_model = [c for c in classes if c.__module__ == model.__name__]
    assert in_model
    assert set(in_model) == {
        c for c in vars(model).values() if isinstance(c, type) and dataclasses.is_dataclass(c)
    }
    for cls in classes:
        section = _section(committed, f"### `{cls.__name__}`")
        assert section.lstrip("\n").startswith(f"`{cls.__module__}.{cls.__qualname__}`")
        annotations: dict[str, object] = {}
        for klass in reversed(cls.__mro__):
            annotations.update(inspect.get_annotations(klass))
        docs = _field_docs(cls)
        rows = [line for line in section.splitlines() if line.startswith("| `")]
        fields = dataclasses.fields(cls)
        assert [_cells(row)[0] for row in rows] == [f"`{f.name}`" for f in fields], cls
        for row, f in zip(rows, fields, strict=True):
            cells = _cells(row)
            assert _same_annotation(cells[1], annotations[f.name]), (cls, f.name, cells)
            assert _unescape_cell(cells[3]) == docs.get(f.name, ""), (cls, f.name, cells)
            if f.default is dataclasses.MISSING:
                if f.default_factory is dataclasses.MISSING:
                    assert cells[2] == "*required*", (cls, f.name)
            elif isinstance(f.default, _SCALARS):
                assert cells[2] == f"`{f.default!r}`", (cls, f.name, cells)


def _changed(value: object) -> int | float:
    """A value of the same type that differs from a numeric default (to load real TOML)."""
    if isinstance(value, int):
        return value + 1
    assert isinstance(value, float)
    return value / 2 if value else 0.5


def test_committed_config_file_sections_load_as_documented(committed: str, tmp_path: Path) -> None:
    section = _section(committed, "### Configuration file")
    assert _docstring(config.load_agent_config) in section
    assert _docstring(config) in section
    by_name = {cls.__name__: cls for cls in CONFIG_CLASSES}
    documented: dict[str, type[Any]] = {}
    for row in section.splitlines():
        match = re.fullmatch(r"\| `\[(\w+)\]` \| `(\w+)` \|", row)
        if match:
            documented[match[1]] = by_name[match[2]]
    assert documented
    for name, cls in documented.items():
        label = _section(committed, f"### `{cls.__name__}`").lstrip("\n").splitlines()[0]
        assert f"`[{name}]`" in label, (name, label)
        field, default = next(
            (f.name, f.default)
            for f in dataclasses.fields(cls)
            if isinstance(f.default, (int, float)) and not isinstance(f.default, bool)
        )
        path = tmp_path / f"{name}.toml"
        new = _changed(default)
        path.write_text(f"[{name}]\n{field} = {json.dumps(new)}\n", encoding="utf-8")
        loaded = config.load_agent_config(path)
        owner = loaded if cls is AgentConfig else getattr(loaded, name)
        assert isinstance(owner, cls)
        assert getattr(owner, field) == new, (name, field)
    for cls in set(CONFIG_CLASSES) - set(documented.values()):
        label = _section(committed, f"### `{cls.__name__}`").lstrip("\n").splitlines()[0]
        assert "TOML section" not in label, label
    # Every name the loader accepts is documented (an unknown section is a ConfigError).
    candidates = {*documented, *(f.name for f in dataclasses.fields(AgentConfig))}
    candidates |= {"agent", "config", "engine", "chaos", "ar1", "baseline", "cca"}
    candidates |= {cls.__name__.lower() for cls in CONFIG_CLASSES}
    accepted = set()
    for name in sorted(candidates):
        path = tmp_path / f"probe_{name}.toml"
        path.write_text(f"[{name}]\n", encoding="utf-8")
        try:
            config.load_agent_config(path)
        except config.ConfigError:
            continue
        accepted.add(name)
    assert accepted == set(documented)
    preset = tmp_path / "preset.toml"
    persona = list_personas()[-1]
    preset.write_text(f'[persona]\npreset = "{persona}"\n', encoding="utf-8")
    assert config.load_agent_config(preset).persona == config.load_persona(persona)


def test_committed_persona_table_matches_every_loaded_value(committed: str) -> None:
    names = list_personas()
    folder = resources.files("cca.personas")
    keys = {n: set(tomllib.loads(folder.joinpath(f"{n}.toml").read_text("utf-8"))) for n in names}
    loaded = {n: config.load_persona(n) for n in names}
    section = _section(committed, "## 8. Shipped personas")
    rows = [line for line in section.splitlines() if line.startswith("| `")]
    fields = dataclasses.fields(Persona)
    assert len(rows) == len(fields)
    for row, f in zip(rows, fields, strict=True):
        cells = _cells(row)
        assert cells[:2] == [f"`{f.name}`", f"`{f.default!r}`"], cells
        for name, cell in zip(names, cells[2:], strict=True):
            value = f"`{getattr(loaded[name], f.name)!r}`"
            assert cell == (f"**{value}**" if f.name in keys[name] else value), (name, cell)


def test_committed_reference_lists_every_persona(committed: str) -> None:
    names = list_personas()
    assert names
    persona_header = next(
        line for line in committed.splitlines() if line.startswith("| Field | Default |")
    )
    assert persona_header == "| Field | Default | " + " | ".join(names) + " |"
    folder = resources.files("cca.personas")
    for name in names:
        text = folder.joinpath(f"{name}.toml").read_text(encoding="utf-8")
        header = itertools.takewhile(lambda line: line.startswith("#"), text.splitlines())
        description = " ".join(" ".join(line.lstrip("#").split()) for line in header)
        bullet = next(line for line in committed.splitlines() if line.startswith(f"- `{name}`: "))
        assert html.unescape(bullet) == f"- `{name}`: {description or '(no description)'}"


def test_committed_equations_quote_the_module_docstrings(committed: str) -> None:
    for name in EQUATION_MODULES:
        doc = _docstring(importlib.import_module(name))
        assert doc, name
        assert doc in _section(committed, f"### `{name}`"), name


def test_committed_environment_rows_name_the_reading_function(committed: str) -> None:
    for variable, path, function in (
        ("CCA_STOCKFISH", "src/cca/engines/stockfish.py", "find_stockfish"),
        ("CCA_WEIGHTS", "src/cca/engines/maia2_human.py", "default_weights_dir"),
        ("GITHUB_TOKEN", "scripts/fetch_stockfish.py", "_request"),
    ):
        lines = (ROOT / path).read_text(encoding="utf-8").splitlines()
        read = re.compile(rf"""(environ|getenv)\W.*["']{variable}["']""")
        number = next(i for i, line in enumerate(lines, 1) if read.search(line))
        cells = _cells(_row(committed, f"`{variable}`"))
        assert cells[1:3] == [f"`{path}:{number}`", f"`{function}`"]
    # Every literal name read anywhere in src/cca and scripts/ has a row.
    literal = re.compile(r"""(?:environ(?:\.\w+\()?\[?|getenv\()\s*["']([A-Za-z_]\w*)["']""")
    in_environ = re.compile(r"""["']([A-Za-z_]\w*)["']\s+(?:not\s+)?in\s+(?:os\.)?environ\b""")
    files = [*(ROOT / "src" / "cca").rglob("*.py"), *(ROOT / "scripts").glob("*.py")]
    names = {
        name
        for path in files
        for pattern in (literal, in_environ)
        for name in pattern.findall(path.read_text(encoding="utf-8"))
    }
    assert names >= {"CCA_STOCKFISH", "CCA_WEIGHTS", "GITHUB_TOKEN"}
    section = _section(committed, "## 11. Environment variables")
    for name in names:
        assert _rows(section, f"`{name}`"), name


def test_committed_security_rows_match_the_audit_script(committed: str) -> None:
    audit = _load(ROOT / "scripts" / "audit_deps.py", "cca_test_audit_deps")
    section = _section(committed, "## 12. Security and supply chain")
    rows = [line for line in section.splitlines() if line.startswith("| `")]
    assert audit.ACCEPTED
    assert [_cells(row)[0] for row in rows] == [f"`{k}`" for k in sorted(audit.ACCEPTED)]
    for row in rows:
        key, reason = _cells(row)
        assert _unescape_cell(reason) == " ".join(audit.ACCEPTED[key.strip("`")].split())
    assert f"`REVIEW_BY` = `{audit.REVIEW_BY.isoformat()}`" in " ".join(section.split())
    assert _docstring(audit) in section


def test_committed_reference_has_no_raw_html_outside_code(committed: str) -> None:
    fence = ""
    for number, line in enumerate(committed.splitlines(), 1):
        if fence:
            fence = "" if line == fence else fence
            continue
        if opening := re.match(r"`{3,}", line):
            fence = opening.group()
            continue
        if line.startswith("<!-- GENERATED FILE"):
            continue
        prose = _CODE_SPAN.sub("", line)
        assert not re.search(r"[<>]|&(?!(?:amp|lt|gt);)", prose), (number, line)


# --- (c) mutation guard: a changed default makes the check fail with a readable diff
def test_check_fails_when_a_dataclass_default_drifts(
    gen: ModuleType,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    out = tmp_path / "reference.md"
    assert gen.main(["--output", str(out)]) == 0
    assert gen.main(["--check", "--output", str(out)]) == 0
    capsys.readouterr()
    field = next(f for f in dataclasses.fields(AgentConfig) if f.name == "fast_budget")
    monkeypatch.setattr(field, "default", 0.75)
    assert gen.main(["--check", "--output", str(out)]) == 1
    captured = capsys.readouterr()
    assert "\n-| `fast_budget` | `float` | `0.6` |" in captured.out
    assert "\n+| `fast_budget` | `float` | `0.75` |" in captured.out
    assert "is stale" in captured.err


def test_check_reports_a_missing_file(
    gen: ModuleType, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert gen.main(["--check", "--output", str(tmp_path / "absent.md")]) == 1
    assert "+# CCA technical reference" in capsys.readouterr().out


def test_diff_lines_stay_separate_without_a_final_newline(
    gen: ModuleType, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    text = gen.render()
    last = text.rstrip("\n").splitlines()[-1]
    out = tmp_path / "reference.md"
    out.write_bytes(text.rstrip("\n").encode("utf-8"))
    assert gen.main(["--check", "--output", str(out)]) == 1
    assert f"\n-{last}\n+{last}\n" in capsys.readouterr().out


def test_render_is_deterministic_and_clean(
    gen: ModuleType, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(gen, "HEADER", gen.HEADER + "trailing blanks   \n")
    first, second = gen.render(), gen.render()
    assert first == second
    assert "\r" not in first
    assert first.endswith("\n")
    assert not first.endswith("\n\n")
    assert all(line == line.rstrip() for line in first.splitlines())


def test_every_date_and_time_in_the_output_comes_from_the_sources(gen: ModuleType) -> None:
    """No timestamps, checked without the calendar: every date or clock time must be an input."""
    inputs = [
        *(ROOT / "src" / "cca").rglob("*.py"),
        *(ROOT / "scripts").glob("*.py"),
        *(ROOT / "src" / "cca" / "personas").glob("*.toml"),
        ROOT / "pyproject.toml",
        ROOT / "engines" / "stockfish.lock.json",
    ]
    sources = "\n".join(p.read_text(encoding="utf-8") for p in inputs)
    audit = gen._load_script("audit_deps.py")
    sources += "\n" + audit.REVIEW_BY.isoformat()  # written as date(y, m, d) in the script
    stamps = re.findall(r"\b\d{4}-\d{2}-\d{2}\b|\b\d{1,2}:\d{2}:\d{2}\b", gen.render())
    assert stamps  # REVIEW_BY at least
    assert [s for s in stamps if s not in sources] == []


CHILD = """
import importlib.util, sys
from pathlib import Path

spec = importlib.util.spec_from_file_location("cca_child_gen", sys.argv[1])
gen = importlib.util.module_from_spec(spec)
sys.modules["cca_child_gen"] = gen
spec.loader.exec_module(gen)
sys.path.insert(0, sys.argv[2])
import holder

extra = [*gen.dataclass_section(holder.Holder), gen.type_name(holder.PARSE)]
Path(sys.argv[3]).write_bytes((gen.render() + "\\n".join(extra)).encode("utf-8"))
"""

HOLDER = """
from __future__ import annotations

import dataclasses
import threading


def _one_of(check):
    def parse(text: str) -> str:
        return text if check(text) else ""

    return parse


@dataclasses.dataclass
class Holder:
    lock: object = dataclasses.field(default_factory=threading.Lock)
    thing: object = dataclasses.field(default_factory=object)


PARSE = _one_of(lambda text: bool(text))
"""


def test_output_is_identical_in_separate_processes(tmp_path: Path) -> None:
    """Hash seeds and object addresses differ between processes; the output must not."""
    (tmp_path / "child.py").write_text(CHILD, encoding="utf-8")
    (tmp_path / "holder.py").write_text(HOLDER, encoding="utf-8")
    outputs = []
    for seed in ("1", "2"):
        out = tmp_path / f"out{seed}.md"
        env = {**os.environ, "PYTHONHASHSEED": seed, "PYTHONIOENCODING": "utf-8"}
        argv = [str(tmp_path / "child.py"), str(GENERATOR), str(tmp_path), str(out)]
        subprocess.run([sys.executable, "-B", *argv], check=True, cwd=ROOT, env=env, timeout=120)
        outputs.append(out.read_bytes().decode("utf-8"))
    assert "| `lock` | `object` | `<unlocked _thread.lock object>` |  |" in outputs[0]
    assert "| `thing` | `object` | `<object object>` |  |" in outputs[0]
    assert outputs[0].endswith("\nstr via _one_of(check=<function <lambda>>)")
    assert outputs[0] == outputs[1]


def test_refuses_a_cca_from_another_tree(
    gen: ModuleType, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(gen, "ROOT", tmp_path)
    with pytest.raises(SystemExit, match="cca was imported from"):
        gen.render()


# --- rendering helpers
def test_fmt_value_is_platform_independent(gen: ModuleType) -> None:
    assert gen.fmt_value(PurePosixPath("a/b")) == "Path('a/b')"
    assert gen.fmt_value(PureWindowsPath("a\\b")) == "Path('a/b')"
    assert gen.fmt_value(frozenset({"b", "a"})) == "{'a', 'b'}"
    assert gen.fmt_value(set()) == "set()"
    assert gen.fmt_value((1,)) == "(1,)"
    assert gen.fmt_value({"k": [1, 2.5]}) == "{'k': [1, 2.5]}"

    @dataclasses.dataclass
    class Point:
        x: int = 1
        where: PurePosixPath = dataclasses.field(default_factory=lambda: PurePosixPath("p"))

    assert gen.fmt_value(Point()) == "Point(x=1, where=Path('p'))"


def test_reprs_lose_their_memory_address(gen: ModuleType) -> None:
    assert gen.fmt_value(threading.Lock()) == "<unlocked _thread.lock object>"
    assert gen.fmt_value([object()]) == "[<object object>]"
    assert gen.fmt_value("x at 0x1F>") == "'x at 0x1F>'"  # strings are values, not addresses

    def check(text: str) -> bool:
        return bool(text)

    def one_of(test: Callable[[str], bool]) -> Callable[[str], str]:
        def parse(text: str) -> str:
            return text if test(text) else ""

        return parse

    shown = gen.type_name(one_of(check))
    assert shown.startswith("str via ")
    assert shown.endswith(
        ".<locals>.one_of(test=<function test_reprs_lose_their_memory_address.<locals>.check>)"
    )
    assert "0x" not in gen.type_name(functools.partial(check))


def test_load_script_registers_the_module_while_it_runs(
    gen: ModuleType, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    scripts = tmp_path / "scripts"
    scripts.mkdir()
    (scripts / "dc_script.py").write_text(
        "from __future__ import annotations\n\nimport dataclasses\n\n\n"
        "@dataclasses.dataclass\nclass Point:\n    x: int = 1\n",
        encoding="utf-8",
    )
    (scripts / "broken.py").write_text("raise ValueError('boom')\n", encoding="utf-8")
    monkeypatch.setattr(gen, "ROOT", tmp_path)
    module = gen._load_script("dc_script.py")  # a dataclass needs its module in sys.modules
    assert module.__name__ == "cca_reference_dc_script"
    assert module.Point().x == 1
    assert "cca_reference_dc_script" not in sys.modules  # removed again
    with pytest.raises(ValueError, match="boom"):
        gen._load_script("broken.py")
    assert "cca_reference_broken" not in sys.modules
    sentinel = ModuleType("cca_reference_dc_script")
    monkeypatch.setitem(sys.modules, "cca_reference_dc_script", sentinel)
    assert gen._load_script("dc_script.py") is not sentinel
    assert sys.modules["cca_reference_dc_script"] is sentinel  # an earlier module is restored
    with pytest.raises(RuntimeError, match="cannot load"):
        gen._load_script("absent.txt")


def test_field_default_forms(gen: ModuleType) -> None:
    @dataclasses.dataclass
    class Inner:
        v: int = 1

    @dataclasses.dataclass
    class Needs:
        v: int

    @dataclasses.dataclass
    class Outer:
        req: int
        plain: float = 0.5
        items: list[int] = dataclasses.field(default_factory=list)
        inner: Inner = dataclasses.field(default_factory=Inner)
        tuned: Inner = dataclasses.field(default_factory=lambda: Inner(2))
        needs: Needs = dataclasses.field(default_factory=lambda: Needs(3))

    got = {f.name: gen.field_default(f) for f in dataclasses.fields(Outer)}
    assert got == {
        "req": "*required*",
        "plain": "`0.5`",
        "items": "`[]`",
        "inner": "`Inner()`",
        "tuned": "`Inner(v=2)`",
        "needs": "`Needs(v=3)`",
    }


def test_code_spans_and_tables_escape_markdown(gen: ModuleType) -> None:
    assert gen.code("") == "*(empty)*"
    assert gen.code("a`b") == "``a`b``"
    assert gen.code("`x") == "`` `x ``"
    assert gen.table(["h"], [["a|b\nc"]]) == ["| h |", "|---|", "| a\\|b c |"]
    assert gen.table(["<h>"], [["a <b> & c"]]) == [
        "| &lt;h&gt; |",
        "|---|",
        "| a &lt;b&gt; &amp; c |",
    ]
    assert gen.block("x ``` y") == ["````text", "x ``` y", "````"]


def test_inline_escapes_html_outside_code_spans_only(gen: ModuleType) -> None:
    assert gen.inline("a <b> & `<c> & d` e > f") == "a &lt;b&gt; &amp; `<c> & d` e &gt; f"
    assert gen.inline("``x ` <y>`` <z>") == "``x ` <y>`` &lt;z&gt;"
    assert gen.inline("open ` <b> ``c``") == "open ` &lt;b&gt; ``c``"
    assert gen.inline("```a`` <b>") == "```a`` &lt;b&gt;"  # runs must match in length
    assert gen.inline("") == ""


# --- CLI introspection
def _bounded(lo: int, hi: int) -> Callable[[str], int]:
    def parse(text: str) -> int:
        return min(hi, max(lo, int(text)))

    return parse


def test_type_name_shows_the_factory_of_a_closure(gen: ModuleType) -> None:
    assert gen.type_name(int) == "int"
    assert gen.type_name(Path) == "Path"
    assert gen.type_name(_bounded(0, 9)) == "int via _bounded(lo=0, hi=9)"  # factory order

    def outer(z: float, a: float) -> Callable[[str], float]:
        return lambda text: float(text) * z * a  # no return annotation: the name is shown

    nested = gen.type_name(outer(2.0, 3.0))  # a factory that cannot be resolved: sorted
    assert nested.startswith("<lambda> via test_type_name_shows_the_factory_of_a_closure.")
    assert nested.endswith(".<locals>.outer(a=3.0, z=2.0)")

    def local(text: str) -> float:
        return float(text)

    assert gen.type_name(local) == "float"  # nothing captured: the return type
    assert gen.type_name(lambda text: text) == "<lambda>"
    assert gen.type_name(functools.partial(int, base=2)) == repr(functools.partial(int, base=2))


def test_cli_section_covers_every_argument_form(gen: ModuleType) -> None:
    parser = argparse.ArgumentParser(
        prog="tool", description="Tool %(prog)s <x>.", epilog="See %(prog)s <docs>."
    )
    parser.add_argument("--verbose", "-v", action="count", default=0, help="louder")
    sub = parser.add_subparsers(dest="cmd")
    run = sub.add_parser("run", help="run <it>", epilog="Run\n  epilog.")
    run.add_argument("files", nargs="+", type=Path, help="inputs")
    run.add_argument("--level", type=int, default=3, choices=[1, 2, 3], help="lvl %(default)s")
    run.add_argument("--secret", help=argparse.SUPPRESS)
    run.add_argument("--mode", required=True)
    run.add_argument("--opt", default=argparse.SUPPRESS)
    run.add_argument("--port", type=_bounded(0, 9), default=5, help="port")
    idle = sub.add_parser("idle", help="nothing", aliases=["rest"])
    idle.add_subparsers(dest="inner").add_parser("deep")  # no help=: still documented

    lines = gen.cli_section(parser)
    text = "\n".join(lines)
    assert lines[:3] == ["### `tool`", "", "Tool tool &lt;x&gt;."]
    assert "| `--verbose, -v` | flag (Count) | `0` |  | louder |" in lines
    assert "Subcommands: `idle`, `run`." in lines
    assert "| `files` | Path, nargs=+ | *required* |  | inputs |" in lines
    assert "| `--level` | int | `3` | `1`, `2`, `3` | lvl 3 |" in lines
    assert "| `--mode` | str | *required* |  |  |" in lines
    assert "| `--opt` | str |  |  |  |" in lines
    assert "| `--port` | int via _bounded(lo=0, hi=9) | `5` |  | port |" in lines
    assert "| `--secret` | str | `None` |  | (hidden from `--help`) |" in lines
    assert "nothing (aliases: `rest`)" in lines
    assert "### `tool rest`" not in lines  # an alias is not a second command
    assert "### `tool idle deep`" in lines
    assert text.index("### `tool idle`") < text.index("### `tool run`")  # sorted
    assert "No arguments." in text.split("### `tool idle deep`")[1]
    run_part = text.split("### `tool run`")[1]
    assert run_part.startswith("\n\nrun &lt;it&gt;\n")
    assert run_part.endswith("| (hidden from `--help`) |\n\nRun epilog.")  # epilog comes last
    assert text.index("See tool &lt;docs&gt;.") < text.index("Subcommands:")
    assert "\n\n\n" not in text


# --- UCI
def test_parse_uci_option_forms(gen: ModuleType) -> None:
    spin = gen.parse_uci_option("option name Move Overhead type spin default 10 min 0 max 5000")
    assert (spin.name, spin.kind, spin.default, spin.min, spin.max) == (
        "Move Overhead",
        "spin",
        "10",
        "0",
        "5000",
    )
    combo = gen.parse_uci_option(
        "option name Style type combo default Solid Play var Solid Play var Wild"
    )
    assert combo.default == "Solid Play"
    assert combo.vars == ("Solid Play", "Wild")
    empty = gen.parse_uci_option("option name Path type string default")
    assert empty.default == ""
    assert gen.parse_uci_option("option name Clear Hash type button").default is None
    with pytest.raises(ValueError, match="not a UCI option"):
        gen.parse_uci_option("id name CCA")
    with pytest.raises(ValueError, match="without name or type"):
        gen.parse_uci_option("option name Lonely")


def test_uci_descriptions_join_when_available(
    gen: ModuleType, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(
        protocol, "UCI_OPTION_HELP", {"CCA_Seed": "a | <b>", "Ghost": "x"}, raising=False
    )
    with_help = gen.section_uci()
    assert _row("\n".join(with_help), "`CCA_Seed`").endswith("| a \\| &lt;b&gt; |")
    assert any("`Ghost`" in line and "no advertised option" in line for line in with_help)

    monkeypatch.delattr(protocol, "UCI_OPTION_HELP", raising=False)
    without = "\n".join(gen.section_uci())
    seed = _row(without, "`CCA_Seed`")
    assert seed.count(" | ") == 6  # still seven columns
    assert seed.endswith("|  |")  # empty description


def test_uci_handshake_must_answer_uciok(gen: ModuleType, monkeypatch: pytest.MonkeyPatch) -> None:
    class Silent:
        def __init__(self, stdin: io.StringIO, stdout: io.StringIO) -> None:
            self.stdout = stdout

        def serve(self) -> None:
            self.stdout.write("id name nothing\n")

    monkeypatch.setattr(protocol, "UciServer", Silent)
    with pytest.raises(RuntimeError, match="uciok"):
        gen.uci_handshake()


# --- dataclasses, personas, equations, constants
@dataclasses.dataclass
class Escaped:
    """Uses <x> & `<y>`."""

    n: int = 1
    """Below <n> & `<m>`."""


def test_every_public_dataclass_is_documented(gen: ModuleType, committed: str) -> None:
    found = gen.discover_dataclasses()
    assert AgentConfig in found
    assert all(not cls.__name__.startswith("_") for cls in found)
    for cls in found:
        assert f"### `{cls.__name__}`" in committed


FAKE_CONFIG = '''
"""Fake config module."""
import dataclasses


@dataclasses.dataclass
class Top:
    a: int = 1


@dataclasses.dataclass
class Part:
    b: int = 2


class Plain:
    pass


PARTS = {{"part": Part}}
NOT_A_MAPPING = 3
BAD = {{"plain": Plain}}


def load_agent_config(raw: dict) -> Top:
    """Loader docstring."""
    unknown = {body}
    return Top()
'''


def _fake_config(tmp_path: Path, body: str) -> ModuleType:
    path = tmp_path / f"fake_config_{len(list(tmp_path.iterdir()))}.py"
    path.write_text(FAKE_CONFIG.format(body=body), encoding="utf-8")
    return _load(path, path.stem)


def test_config_file_sections_are_read_from_the_loader(
    gen: ModuleType, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    assert gen.config_file_sections()[0] == ("agent", AgentConfig)
    monkeypatch.setattr(gen, "config", _fake_config(tmp_path, 'set(raw) - {"top", *PARTS}'))
    assert gen.config_file_sections() == [("top", gen.config.Top), ("part", gen.config.Part)]
    lines = gen._config_file()
    assert "| `[top]` | `Top` |" in lines
    assert "Fake config module." in lines
    assert "Loader docstring." in lines
    for body, kind, error in (
        ("set(raw)", RuntimeError, "expected one"),
        ('set(raw) - {"top"} - {"x"}', RuntimeError, "expected one"),
        ('set(raw) - {"top", "again"}', RuntimeError, "ambiguous"),
        ('set(raw) - {"top", "top", *PARTS}', RuntimeError, "ambiguous"),
        ('set(raw) - {"top", PARTS}', TypeError, "cannot read section PARTS"),
        ('set(raw) - {"top", *NOT_A_MAPPING}', TypeError, "NOT_A_MAPPING is not a mapping"),
        ('set(raw) - {"top", *BAD}', RuntimeError, "must map a name to a dataclass"),
    ):
        monkeypatch.setattr(gen, "config", _fake_config(tmp_path, body))
        with pytest.raises(kind, match=error):
            gen.config_file_sections()


def test_dataclass_section_labels_every_toml_section(gen: ModuleType) -> None:
    assert gen.dataclass_section(Escaped)[2] == f"`{Escaped.__module__}.Escaped`."
    labelled = gen.dataclass_section(Escaped, ["a", "b"])[2]
    assert labelled.endswith(".Escaped`; TOML section `[a]`, `[b]`.")


def test_dataclass_section_escapes_docstrings(gen: ModuleType) -> None:
    lines = gen.dataclass_section(Escaped)
    assert "Uses &lt;x&gt; &amp; `<y>`." in lines
    assert "| `n` | `int` | `1` | Below &lt;n&gt; &amp; `<m>`. |" in lines


def test_field_sources_read_annotations_and_attribute_docstrings(gen: ModuleType) -> None:
    sources = gen.field_sources(AgentConfig)
    assert sources["persona"] == ("Persona", "")
    annotation, doc = sources["fast_budget"]
    assert annotation == "float"
    assert "reflex mode" in doc


def test_missing_source_nodes_are_errors(gen: ModuleType, tmp_path: Path) -> None:
    path = tmp_path / "empty.py"
    path.write_text("X = 1\n", encoding="utf-8")
    with pytest.raises(RuntimeError, match="no top-level function"):
        gen._function_node(path, "absent")

    ghost = type("Ghost", (), {"__module__": "cca.core.types"})
    with pytest.raises(RuntimeError, match="no top-level class Ghost"):
        gen._class_node(ghost)


def test_persona_cells_are_bold_exactly_when_the_toml_sets_the_field(gen: ModuleType) -> None:
    names = list_personas()
    folder = resources.files("cca.personas")
    keys = {n: set(tomllib.loads(folder.joinpath(f"{n}.toml").read_text("utf-8"))) for n in names}
    rows = [
        line
        for line in gen.section_personas()
        if line.startswith("| `") and line.count(" | ") == len(names) + 1
    ]
    assert len(rows) == len(dataclasses.fields(Persona))
    for line, f in zip(rows, dataclasses.fields(Persona), strict=True):
        cells = [c.strip() for c in line.strip("|").split(" | ")]
        assert cells[0] == f"`{f.name}`"
        for name, cell in zip(names, cells[2:], strict=True):
            assert cell.startswith("**") == (f.name in keys[name]), (name, f.name, cell)


def test_persona_descriptions_are_escaped(gen: ModuleType, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(gen, "toml_description", lambda text: "a <b> & c")
    bullets = [line for line in gen.section_personas() if line.startswith("- `")]
    assert bullets
    assert all(line.endswith("`: a &lt;b&gt; &amp; c") for line in bullets)


def test_toml_description_is_the_header_comment(gen: ModuleType) -> None:
    text = "# First line.\n#  second\nname = 'x'\n# not part of it\n"
    assert gen.toml_description(text) == "First line. second"
    assert gen.toml_description("name = 'x'\n") == ""


def test_equations_skip_modules_that_do_not_exist(
    gen: ModuleType, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(
        gen, "EQUATION_MODULES", ("cca.does_not_exist", "nopkg.mod", "cca.chaos.lorenz")
    )
    text = "\n".join(gen.section_equations())
    assert "### `cca.chaos.lorenz`" in text
    assert "does_not_exist" not in text
    assert "nopkg" not in text


def test_numeric_constants_fold_arithmetic_on_numbers(gen: ModuleType, tmp_path: Path) -> None:
    path = tmp_path / "consts.py"
    path.write_text(
        "A = 1\nB: float = 2.5\nC = (1, -2.0)\nD = 'x'\nE = True\nF = foo()\n"
        "G, H = 1, 2\nI = ()\nJ = -3\nx.y = 4\nK: int\nL = {[]: 1}\n"
        "M = 64 * 1024\nN = None\nO = (1.0, 3 * 3600.0)\nP = (None, (180, 2))\n"
        "Q = [2 ** 10, None]\nR = -(7 // 2) % 5 - +1 / 4\nS = 'a' * 2\nT = A * 2\n"
        "U = (None,)\nV = True + 1\nW = (1, 'x')\nX = f(1) + 1\nY = ~1\n"
        "Z = 1 << 4 | 3 & 6 ^ 8 >> 1\nAA = (1, 2) * 2\nAB = -None\n",
        encoding="utf-8",
    )
    assert gen.numeric_constants(path) == [
        ("A", "1", ""),
        ("B", "2.5", ""),
        ("C", "(1, -2.0)", ""),
        ("J", "-3", ""),
        ("M", "65536", "64 * 1024"),
        ("O", "(1.0, 10800.0)", "(1.0, 3 * 3600.0)"),
        ("P", "(None, (180, 2))", ""),
        ("Q", "[1024, None]", "[2 ** 10, None]"),
        ("R", "1.75", "-(7 // 2) % 5 - +1 / 4"),
        ("Y", "-2", "~1"),
        ("Z", repr(1 << 4 | 3 & 6 ^ 8 >> 1), "1 << 4 | 3 & 6 ^ 8 >> 1"),
    ]


def test_constants_section_shows_the_expression(
    gen: ModuleType, monkeypatch: pytest.MonkeyPatch
) -> None:
    module = ROOT / "src" / "cca" / "chaos" / "lorenz.py"
    monkeypatch.setattr(gen, "_package_files", lambda: [module])
    found = [("M", "65536", "64 * 1024"), ("A", "1", "")]
    monkeypatch.setattr(gen, "numeric_constants", lambda path: found if path == module else [])
    lines = gen.section_constants()
    assert "| Module | Name | Value | Expression |" in lines
    assert "| `cca.chaos.lorenz` | `M` | `65536` | `64 * 1024` |" in lines
    assert "| `cca.chaos.lorenz` | `A` | `1` |  |" in lines


# --- environment variables
ENV_SOURCE = '''
import os
from os import environ, getenv

A = os.environ.get("MOD_LEVEL")


def outer():
    """Outer summary.

    More text.
    """
    def inner():
        return os.getenv("INNER")
    return inner


class C:
    def m(self, key):
        """Method summary."""
        os.environ["WRITTEN"] = "1"
        x = environ["READ"]
        y = "PRESENT" in os.environ
        z = getenv(key)
        w = os.environ.copy()
        os.environ.setdefault("DEFAULTED", "1")
        v = "ABSENT" not in environ
        return os.environ.pop("POPPED", None)


class Settings:
    """A class docstring is not a function summary."""

    HOME = os.environ.get("CLASS_LEVEL")
'''


def test_env_reads_find_every_access_form(gen: ModuleType) -> None:
    got = {
        r.name: (r.where, r.function, r.access, r.summary)
        for r in gen.env_reads(ENV_SOURCE, "x.py")
    }
    assert got == {
        "MOD_LEVEL": ("x.py", "<module>", "environ.get()", ""),
        "INNER": ("x.py", "outer.inner", "getenv()", ""),
        "WRITTEN": ("x.py", "C.m", "environ[...] (write)", "Method summary."),
        "READ": ("x.py", "C.m", "environ[...]", "Method summary."),
        "PRESENT": ("x.py", "C.m", "in environ", "Method summary."),
        "<dynamic: key>": ("x.py", "C.m", "getenv()", "Method summary."),
        "DEFAULTED": ("x.py", "C.m", "environ.setdefault()", "Method summary."),
        "ABSENT": ("x.py", "C.m", "in environ", "Method summary."),
        "POPPED": ("x.py", "C.m", "environ.pop()", "Method summary."),
        "CLASS_LEVEL": ("x.py", "Settings", "environ.get()", ""),
    }
    lines = {r.name: r.line for r in gen.env_reads(ENV_SOURCE, "x.py")}
    assert lines["MOD_LEVEL"] == 5


# --- supply chain
def test_security_section_validates_the_audit_script(
    gen: ModuleType, monkeypatch: pytest.MonkeyPatch
) -> None:
    text = "\n".join(gen.section_security())
    audit = gen._load_script("audit_deps.py")
    for advisory in audit.ACCEPTED:
        assert f"| `{advisory}` |" in text
    assert audit.REVIEW_BY.isoformat() in text

    monkeypatch.setattr(
        gen, "_load_script", lambda name: SimpleNamespace(ACCEPTED={}, REVIEW_BY="2027-01-01")
    )
    with pytest.raises(TypeError, match="REVIEW_BY must be a date"):
        gen.section_security()
